repo:
  private: true
#   secretName: {{ template "fullname" . }}

# Default values for the broker-skeleton
# Image to use
image:
  repository: harbor.arfa.wise-paas.com/develop_joanne/example-blob-golang
  tag: 0.0.1
  # ImagePullPolicy; valid values are "IfNotPresent", "Never", and "Always"
  pullPolicy: Always
 
imagePullSecrets: 
  - name: harborsecret2

replicas: 1

ingress:
  enabled: true
  annotations: {}
  hosts: 
    - host: blobexample.golang.eks002.en.internal
      paths: [/]
  tls: []
# http://postgresql-cadev-ews001.bm.wise-paas.com.cn

service:
  type: ClusterIP
  port: 8080
 
resources:
  limits:
    cpu: "150m"
    memory: "64Mi"
    ephemeral-storage: "32Mi"
    
appSecretName: test0925